### ISSUE TITLE
Add Action Methods for Truck and Motorbike

### ISSUE THREAD

**Issue by mirasoldavila13** [mirasoldavila13/Vehicle-Builder-CLI#4]
## User Story:

AS A developer
I WANT TO add action methods for trucks and motorbikes in the CLI
SO THAT users can perform specific actions like towing with trucks and wheelies with motorbikes.

## Acceptance Criteria:

1. The `tow` action is implemented for trucks in the CLI.
2. The `wheelie` action is implemented for motorbikes in the CLI.
3. The CLI properly displays the results of these actions in the command-line interface.

## Tasks:

- [x] Implement the `tow` action in the `performActions` method for trucks.
- [x] Implement the `wheelie` action in the `performActions` method for motorbikes.
- [x] Test the actions to ensure they work as expected.
